language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "A5KvfhAeEoXFrZt8LREAt0VlObW+WzOeD5m0ojAWgUDRrbklw1k0dOkBhiELNqw/zKsdGIZGYn6Si/2IfMV0+HrCva5AP0/izJJden+yXU51Dr3isK3tlYejArz6uvx1rMhcWgStbH46nQXla6zrvJGmFnXU78D4ZOBUknYIULV+e0rEUDVvx/izKP3pOSTmXapdVA/nreArsUDj8HHcylDqPMd5vCEm9aVZVZpiG83cuIl4mgX4ZE+wEvKLCDLEpDx78W9pwUmegmIkLXvEKZxtHZKSzimnog2rSN3pOEXhAgkdd5s3s9X3ZoMBRGpF/iTshkBkC3Glf1fwspH63GP/aRPgIIEJJghFxHylCmppqjF4ygPGToaEINriP7ygB645pdtN/IOoKoHVzE8hiQmx4nMZv30VyJtcMyWJlKZPK7MeyLa5zTdR7yA5vg7rumydjS7moL5S/AR9qZWfb3mda+IyrGBPevsbQl7xBJ6iwFXD9Mn9Y8TYUnJMYJMsfWf3tunYL3UD67h/gSeKAgX7OaCTLAd7C6+x+CxnJeNsmxfMfEZKqvCPEe93Ix77pw9DM0r/L/rajU7Lq2DI2fiaZQoaZv3vlcX9O5ylxEOfvThfsVo5Znh5PG6eH6+iWphLXTOIPpMqeuEuk/mYXdD5w3zrAHQ734B+GSEaJMw="
  api_key: # 80fb
    secure: "oJdelRmUouJjOeQy4avUk9Gw8dhER1kG8GDk7VmEQC0H+7mVZfOyW/DvpCebyUsJxbUexjrawOlRjXKVh6yql8/HmK1j2dDmkWbfhdTsyB8oaIMtMv0p4by7B36QerbkKqsZ7tXN87rXBKExoVBnOR3BRcUsD/uwttGWzVCZ+ifEQioSfplaSv0LVQ4n7JcCGq4khABDwtEREoCwRgcuHGRsPoO3u3bWMuncyGo59rYhgEOq3inUVnBUgaEpwvwKCLZdOX1WUSe0y/lORHxglzxjtaSX/YHEbN7gS42SvfoaGiUwS5EhsTXykXI5yvomd0bK3VTGefvJsAScbv9okTY51p8ceEWh9/3PvJ+tL/gSG58NZYEDsVvRSIPqGx24IlVLoeuTv0RQyi4XTKza7cMyKJGfZRh5rM5eithu9DuvsonnEIP6psFo/+/rt8EITfgNtLVdb1qctOz07epy+MSyErqmayIST0Sjr4nfjn4qcq3cuCeO5ZHbLUihbvfH/4bry6gZjRL6WC2I02LL1UMUGgV9dZpugtQCiLZMsHj8VEgcM5fTXdPlfy1c/eFqNAiU4IjVihATv5616ThmCAR95YeMmhVSuTDgHvXesV34xvbt0M8vdj6m7w9+xY+lNKzUzmUKFrjQnSVcxbtbyzb09oheo1kHaaKBLglXlLA="
  on:
    tags: true
    node: lts/*
